name: Setup CodeAnalysis .NET

on:
  push:
    branches: [ main, dev, feature/*, fix/*, release/* ]

  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x
      # dotnet-quality: 'preview' # When using preview versions
        dotnet-quality: 'ga' # General Availability

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    # CodeAnalysis.Extensions

    - name: Restore CodeAnalysis.Extensions
      run: dotnet restore ./src/*/CodeAnalysis.Extensions.csproj

    - name: Build CodeAnalysis.Extensions
      run: dotnet build ./src/*/CodeAnalysis.Extensions.csproj --no-restore  -c Release

    - name: Pack CodeAnalysis.Extensions
      run: dotnet pack ./src/*/CodeAnalysis.Extensions.csproj --no-restore -o ~/nuget  -c Release

    # CodeAnalysis.SourceBuilder

    - name: Restore CodeAnalysis.SourceBuilder
      run: dotnet restore ./src/*/CodeAnalysis.SourceBuilder.csproj

    - name: Build CodeAnalysis.SourceBuilder
      run: dotnet build ./src/*/CodeAnalysis.SourceBuilder.csproj --no-restore  -c Release

    - name: Pack CodeAnalysis.SourceBuilder
      run: dotnet pack ./src/*/CodeAnalysis.SourceBuilder.csproj --no-restore -o ~/nuget  -c Release

    # CodeAnalysis

    - name: Restore CodeAnalysis
      run: dotnet restore ./src/*/CodeAnalysis.csproj

    - name: Build CodeAnalysis
      run: dotnet build ./src/*/CodeAnalysis.csproj --no-restore  -c Release

    - name: Pack CodeAnalysis
      run: dotnet pack ./src/*/CodeAnalysis.csproj --no-restore -o ~/nuget  -c Release

      # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s https://api.nuget.org/v3/index.json
        -k ${{ secrets.NuGetSourcePassword }}
        --skip-duplicate
